ti.cpp:4:1: warning: AQK01: Need #include <stl_pair.h> for symbol std::pair<int, int>
std::pair<int, int> p;
^
ti.cpp:5:1: warning: AQK01: Need #include <stringfwd.h> for symbol std::string
std::string s;
^
ti.cpp:5:1: warning: AQK01: Need #include <basic_string.tcc> for symbol std::string
ti.cpp:5:13: warning: AQK01: Need #include <basic_string.h> for symbol basic_string
std::string s;
            ^
4 warnings generated.
