In file included from groups/csa/csastil/csastil_includeorder.t.cpp:3:
groups/csa/csastil/csastil_includeorder.t.h:15:0: warning: SHO: package header out of order
#ifndef INCLUDED_CSASTIL_TESTA
^
groups/csa/csastil/csastil_includeorder.t.h:24:0: warning: SHO: package header coming late
#ifndef INCLUDED_CSASTIL_TESTD
^
groups/csa/csastil/csastil_includeorder.t.h:27:0: warning: SHO: group header out of order
#ifndef INCLUDED_CSAPKGA_TESTB
^
groups/csa/csastil/csastil_includeorder.t.h:39:0: warning: SHO: group header out of order
#ifndef INCLUDED_CSAPKGB_TESTB
^
groups/csa/csastil/csastil_includeorder.t.h:54:0: warning: SHO: component header out of order
#ifndef INCLUDED_CSAPKGA_TESTD
^
5 warnings generated.
