In file included from groups/csa/csastil/csastil_templatetypename.t.cpp:3:
groups/csa/csastil/csastil_templatetypename.t.h:14:0: warning: template parameter uses typename
            template <typename S> TemplateTypenameBad();
^
groups/csa/csastil/csastil_templatetypename.t.h:15:0: warning: template parameter uses typename
            template <typename S> void foo();
^
groups/csa/csastil/csastil_templatetypename.t.h:10:0: warning: template parameter uses typename
        template <typename T>
^
groups/csa/csastil/csastil_templatetypename.t.h:21:0: warning: template parameter uses typename
            template <typename S> TemplateTypenameMember();
^
groups/csa/csastil/csastil_templatetypename.t.h:22:0: warning: template parameter uses typename
            template <typename S> void foo();
^
groups/csa/csastil/csastil_templatetypename.t.h:25:0: warning: template parameter uses typename
        template <typename T>
^
groups/csa/csastil/csastil_templatetypename.t.h:41:0: warning: template parameter uses typename
template <typename T>
^
groups/csa/csastil/csastil_templatetypename.t.cpp:5:0: warning: template parameter uses typename
template <typename T>
^
groups/csa/csastil/csastil_templatetypename.t.cpp:5:0: warning: TR04: declaration of 'bad' at global scope
template <typename T>
^~~~~~
groups/csa/csastil/csastil_templatetypename.t.cpp:8:0: warning: template parameter uses typename
template <typename T>
^
groups/csa/csastil/csastil_templatetypename.t.cpp:8:0: warning: TR04: declaration of 'good' at global scope
template <typename T>
^~~~~~
groups/csa/csastil/csastil_templatetypename.t.cpp:17:0: warning: template parameter uses typename
            template <typename T>
^
12 warnings generated.
