int main()
{
    extern int            a;
    extern double         d;
    extern const int      ca;
    extern const double   cd;
    extern int           *pa;
    extern double        *pd;
    extern const int     *pca;
    extern const double  *pcd;
    extern int&           ra;
    extern double&        rd;
    extern const int&     rca;
    extern const double&  rcd;
    extern int            o;
    extern double         od;

    if (   a == 1 ) return 1; if (   a < 1 ) return 1;
    if (   a == 1.) return 1; if (   a < 1.) return 1;
    if (   d == 1 ) return 1; if (   d < 1 ) return 1;
    if (   d == 1.) return 1; if (   d < 1.) return 1;
    if (  ca == 1 ) return 1; if (  ca < 1 ) return 1;
    if (  ca == 1.) return 1; if (  ca < 1.) return 1;
    if (  cd == 1 ) return 1; if (  cd < 1 ) return 1;
    if (  cd == 1.) return 1; if (  cd < 1.) return 1;
    if ( *pa == 1 ) return 1; if ( *pa < 1 ) return 1;
    if ( *pa == 1.) return 1; if ( *pa < 1.) return 1;
    if ( *pd == 1 ) return 1; if ( *pd < 1 ) return 1;
    if ( *pd == 1.) return 1; if ( *pd < 1.) return 1;
    if (*pca == 1 ) return 1; if (*pca < 1 ) return 1;
    if (*pca == 1.) return 1; if (*pca < 1.) return 1;
    if (*pcd == 1 ) return 1; if (*pcd < 1 ) return 1;
    if (*pcd == 1.) return 1; if (*pcd < 1.) return 1;
    if (  ra == 1 ) return 1; if (  ra < 1 ) return 1;
    if (  ra == 1.) return 1; if (  ra < 1.) return 1;
    if (  rd == 1 ) return 1; if (  rd < 1 ) return 1;
    if (  rd == 1.) return 1; if (  rd < 1.) return 1;
    if ( rca == 1 ) return 1; if ( rca < 1 ) return 1;
    if ( rca == 1.) return 1; if ( rca < 1.) return 1;
    if ( rcd == 1 ) return 1; if ( rcd < 1 ) return 1;
    if ( rcd == 1.) return 1; if ( rcd < 1.) return 1;
    if (1  ==    a) return 1; if (1  <    a) return 1;
    if (1. ==    a) return 1; if (1. <    a) return 1;
    if (1  ==    d) return 1; if (1  <    d) return 1;
    if (1. ==    d) return 1; if (1. <    d) return 1;
    if (1  ==   ca) return 1; if (1  <   ca) return 1;
    if (1. ==   ca) return 1; if (1. <   ca) return 1;
    if (1  ==   cd) return 1; if (1  <   cd) return 1;
    if (1. ==   cd) return 1; if (1. <   cd) return 1;
    if (1  ==  *pa) return 1; if (1  <  *pa) return 1;
    if (1. ==  *pa) return 1; if (1. <  *pa) return 1;
    if (1  ==  *pd) return 1; if (1  <  *pd) return 1;
    if (1. ==  *pd) return 1; if (1. <  *pd) return 1;
    if (1  == *pca) return 1; if (1  < *pca) return 1;
    if (1. == *pca) return 1; if (1. < *pca) return 1;
    if (1  == *pcd) return 1; if (1  < *pcd) return 1;
    if (1. == *pcd) return 1; if (1. < *pcd) return 1;
    if (1  ==   ra) return 1; if (1  <   ra) return 1;
    if (1. ==   ra) return 1; if (1. <   ra) return 1;
    if (1  ==   rd) return 1; if (1  <   rd) return 1;
    if (1. ==   rd) return 1; if (1. <   rd) return 1;
    if (1  ==  rca) return 1; if (1  <  rca) return 1;
    if (1. ==  rca) return 1; if (1. <  rca) return 1;
    if (1  ==  rcd) return 1; if (1  <  rcd) return 1;
    if (1. ==  rcd) return 1; if (1. <  rcd) return 1;
    if ((   a == 1 ) << (   a < 1 )) return 1;
    if ((   a == 1.) << (   a < 1.)) return 1;
    if ((   d == 1 ) << (   d < 1 )) return 1;
    if ((   d == 1.) << (   d < 1.)) return 1;
    if ((  ca == 1 ) << (  ca < 1 )) return 1;
    if ((  ca == 1.) << (  ca < 1.)) return 1;
    if ((  cd == 1 ) << (  cd < 1 )) return 1;
    if ((  cd == 1.) << (  cd < 1.)) return 1;
    if (( *pa == 1 ) << ( *pa < 1 )) return 1;
    if (( *pa == 1.) << ( *pa < 1.)) return 1;
    if (( *pd == 1 ) << ( *pd < 1 )) return 1;
    if (( *pd == 1.) << ( *pd < 1.)) return 1;
    if ((*pca == 1 ) << (*pca < 1 )) return 1;
    if ((*pca == 1.) << (*pca < 1.)) return 1;
    if ((*pcd == 1 ) << (*pcd < 1 )) return 1;
    if ((*pcd == 1.) << (*pcd < 1.)) return 1;
    if ((  ra == 1 ) << (  ra < 1 )) return 1;
    if ((  ra == 1.) << (  ra < 1.)) return 1;
    if ((  rd == 1 ) << (  rd < 1 )) return 1;
    if ((  rd == 1.) << (  rd < 1.)) return 1;
    if (( rca == 1 ) << ( rca < 1 )) return 1;
    if (( rca == 1.) << ( rca < 1.)) return 1;
    if (( rcd == 1 ) << ( rcd < 1 )) return 1;
    if (( rcd == 1.) << ( rcd < 1.)) return 1;
    if ((   a == 1 ) != (   a < 1 )) return 1;
    if ((   a == 1.) != (   a < 1.)) return 1;
    if ((   d == 1 ) != (   d < 1 )) return 1;
    if ((   d == 1.) != (   d < 1.)) return 1;
    if ((  ca == 1 ) != (  ca < 1 )) return 1;
    if ((  ca == 1.) != (  ca < 1.)) return 1;
    if ((  cd == 1 ) != (  cd < 1 )) return 1;
    if ((  cd == 1.) != (  cd < 1.)) return 1;
    if (( *pa == 1 ) != ( *pa < 1 )) return 1;
    if (( *pa == 1.) != ( *pa < 1.)) return 1;
    if (( *pd == 1 ) != ( *pd < 1 )) return 1;
    if (( *pd == 1.) != ( *pd < 1.)) return 1;
    if ((*pca == 1 ) != (*pca < 1 )) return 1;
    if ((*pca == 1.) != (*pca < 1.)) return 1;
    if ((*pcd == 1 ) != (*pcd < 1 )) return 1;
    if ((*pcd == 1.) != (*pcd < 1.)) return 1;
    if ((  ra == 1 ) != (  ra < 1 )) return 1;
    if ((  ra == 1.) != (  ra < 1.)) return 1;
    if ((  rd == 1 ) != (  rd < 1 )) return 1;
    if ((  rd == 1.) != (  rd < 1.)) return 1;
    if (( rca == 1 ) != ( rca < 1 )) return 1;
    if (( rca == 1.) != ( rca < 1.)) return 1;
    if (( rcd == 1 ) != ( rcd < 1 )) return 1;
    if (( rcd == 1.) != ( rcd < 1.)) return 1;
    if ((1  ==    a) << (1  <    a)) return 1;
    if ((1. ==    a) << (1. <    a)) return 1;
    if ((1  ==    d) << (1  <    d)) return 1;
    if ((1. ==    d) << (1. <    d)) return 1;
    if ((1  ==   ca) << (1  <   ca)) return 1;
    if ((1. ==   ca) << (1. <   ca)) return 1;
    if ((1  ==   cd) << (1  <   cd)) return 1;
    if ((1. ==   cd) << (1. <   cd)) return 1;
    if ((1  ==  *pa) << (1  <  *pa)) return 1;
    if ((1. ==  *pa) << (1. <  *pa)) return 1;
    if ((1  ==  *pd) << (1  <  *pd)) return 1;
    if ((1. ==  *pd) << (1. <  *pd)) return 1;
    if ((1  == *pca) << (1  < *pca)) return 1;
    if ((1. == *pca) << (1. < *pca)) return 1;
    if ((1  == *pcd) << (1  < *pcd)) return 1;
    if ((1. == *pcd) << (1. < *pcd)) return 1;
    if ((1  ==   ra) << (1  <   ra)) return 1;
    if ((1. ==   ra) << (1. <   ra)) return 1;
    if ((1  ==   rd) << (1  <   rd)) return 1;
    if ((1. ==   rd) << (1. <   rd)) return 1;
    if ((1  ==  rca) << (1  <  rca)) return 1;
    if ((1. ==  rca) << (1. <  rca)) return 1;
    if ((1  ==  rcd) << (1  <  rcd)) return 1;
    if ((1. ==  rcd) << (1. <  rcd)) return 1;
    if (   a == o ) return 1; if (   a < o ) return 1;
    if (   a == od) return 1; if (   a < od) return 1;
    if (   d == o ) return 1; if (   d < o ) return 1;
    if (   d == od) return 1; if (   d < od) return 1;
    if (  ca == o ) return 1; if (  ca < o ) return 1;
    if (  ca == od) return 1; if (  ca < od) return 1;
    if (  cd == o ) return 1; if (  cd < o ) return 1;
    if (  cd == od) return 1; if (  cd < od) return 1;
    if ( *pa == o ) return 1; if ( *pa < o ) return 1;
    if ( *pa == od) return 1; if ( *pa < od) return 1;
    if ( *pd == o ) return 1; if ( *pd < o ) return 1;
    if ( *pd == od) return 1; if ( *pd < od) return 1;
    if (*pca == o ) return 1; if (*pca < o ) return 1;
    if (*pca == od) return 1; if (*pca < od) return 1;
    if (*pcd == o ) return 1; if (*pcd < o ) return 1;
    if (*pcd == od) return 1; if (*pcd < od) return 1;
    if (  ra == o ) return 1; if (  ra < o ) return 1;
    if (  ra == od) return 1; if (  ra < od) return 1;
    if (  rd == o ) return 1; if (  rd < o ) return 1;
    if (  rd == od) return 1; if (  rd < od) return 1;
    if ( rca == o ) return 1; if ( rca < o ) return 1;
    if ( rca == od) return 1; if ( rca < od) return 1;
    if ( rcd == o ) return 1; if ( rcd < o ) return 1;
    if ( rcd == od) return 1; if ( rcd < od) return 1;
    if (o  ==    a) return 1; if (o  <    a) return 1;
    if (od ==    a) return 1; if (od <    a) return 1;
    if (o  ==    d) return 1; if (o  <    d) return 1;
    if (od ==    d) return 1; if (od <    d) return 1;
    if (o  ==   ca) return 1; if (o  <   ca) return 1;
    if (od ==   ca) return 1; if (od <   ca) return 1;
    if (o  ==   cd) return 1; if (o  <   cd) return 1;
    if (od ==   cd) return 1; if (od <   cd) return 1;
    if (o  ==  *pa) return 1; if (o  <  *pa) return 1;
    if (od ==  *pa) return 1; if (od <  *pa) return 1;
    if (o  ==  *pd) return 1; if (o  <  *pd) return 1;
    if (od ==  *pd) return 1; if (od <  *pd) return 1;
    if (o  == *pca) return 1; if (o  < *pca) return 1;
    if (od == *pca) return 1; if (od < *pca) return 1;
    if (o  == *pcd) return 1; if (o  < *pcd) return 1;
    if (od == *pcd) return 1; if (od < *pcd) return 1;
    if (o  ==   ra) return 1; if (o  <   ra) return 1;
    if (od ==   ra) return 1; if (od <   ra) return 1;
    if (o  ==   rd) return 1; if (o  <   rd) return 1;
    if (od ==   rd) return 1; if (od <   rd) return 1;
    if (o  ==  rca) return 1; if (o  <  rca) return 1;
    if (od ==  rca) return 1; if (od <  rca) return 1;
    if (o  ==  rcd) return 1; if (o  <  rcd) return 1;
    if (od ==  rcd) return 1; if (od <  rcd) return 1;
    if ((   a == o ) << (   a < o )) return 1;
    if ((   a == od) << (   a < od)) return 1;
    if ((   d == o ) << (   d < o )) return 1;
    if ((   d == od) << (   d < od)) return 1;
    if ((  ca == o ) << (  ca < o )) return 1;
    if ((  ca == od) << (  ca < od)) return 1;
    if ((  cd == o ) << (  cd < o )) return 1;
    if ((  cd == od) << (  cd < od)) return 1;
    if (( *pa == o ) << ( *pa < o )) return 1;
    if (( *pa == od) << ( *pa < od)) return 1;
    if (( *pd == o ) << ( *pd < o )) return 1;
    if (( *pd == od) << ( *pd < od)) return 1;
    if ((*pca == o ) << (*pca < o )) return 1;
    if ((*pca == od) << (*pca < od)) return 1;
    if ((*pcd == o ) << (*pcd < o )) return 1;
    if ((*pcd == od) << (*pcd < od)) return 1;
    if ((  ra == o ) << (  ra < o )) return 1;
    if ((  ra == od) << (  ra < od)) return 1;
    if ((  rd == o ) << (  rd < o )) return 1;
    if ((  rd == od) << (  rd < od)) return 1;
    if (( rca == o ) << ( rca < o )) return 1;
    if (( rca == od) << ( rca < od)) return 1;
    if (( rcd == o ) << ( rcd < o )) return 1;
    if (( rcd == od) << ( rcd < od)) return 1;
    if ((o  ==    a) << (o  <    a)) return 1;
    if ((od ==    a) << (od <    a)) return 1;
    if ((o  ==    d) << (o  <    d)) return 1;
    if ((od ==    d) << (od <    d)) return 1;
    if ((o  ==   ca) << (o  <   ca)) return 1;
    if ((od ==   ca) << (od <   ca)) return 1;
    if ((o  ==   cd) << (o  <   cd)) return 1;
    if ((od ==   cd) << (od <   cd)) return 1;
    if ((o  ==  *pa) << (o  <  *pa)) return 1;
    if ((od ==  *pa) << (od <  *pa)) return 1;
    if ((o  ==  *pd) << (o  <  *pd)) return 1;
    if ((od ==  *pd) << (od <  *pd)) return 1;
    if ((o  == *pca) << (o  < *pca)) return 1;
    if ((od == *pca) << (od < *pca)) return 1;
    if ((o  == *pcd) << (o  < *pcd)) return 1;
    if ((od == *pcd) << (od < *pcd)) return 1;
    if ((o  ==   ra) << (o  <   ra)) return 1;
    if ((od ==   ra) << (od <   ra)) return 1;
    if ((o  ==   rd) << (o  <   rd)) return 1;
    if ((od ==   rd) << (od <   rd)) return 1;
    if ((o  ==  rca) << (o  <  rca)) return 1;
    if ((od ==  rca) << (od <  rca)) return 1;
    if ((o  ==  rcd) << (o  <  rcd)) return 1;
    if ((od ==  rcd) << (od <  rcd)) return 1;
    if(a==1)return 1;if(a<1)return 1;
    if(a==1.)return 1;if(a<1.)return 1;
    if(d==1)return 1;if(d<1)return 1;
    if(d==1.)return 1;if(d<1.)return 1;
    if(ca==1)return 1;if(ca<1)return 1;
    if(ca==1.)return 1;if(ca<1.)return 1;
    if(cd==1)return 1;if(cd<1)return 1;
    if(cd==1.)return 1;if(cd<1.)return 1;
    if(*pa==1)return 1;if(*pa<1)return 1;
    if(*pa==1.)return 1;if(*pa<1.)return 1;
    if(*pd==1)return 1;if(*pd<1)return 1;
    if(*pd==1.)return 1;if(*pd<1.)return 1;
    if(*pca==1)return 1;if(*pca<1)return 1;
    if(*pca==1.)return 1;if(*pca<1.)return 1;
    if(*pcd==1)return 1;if(*pcd<1)return 1;
    if(*pcd==1.)return 1;if(*pcd<1.)return 1;
    if(ra==1)return 1;if(ra<1)return 1;
    if(ra==1.)return 1;if(ra<1.)return 1;
    if(rd==1)return 1;if(rd<1)return 1;
    if(rd==1.)return 1;if(rd<1.)return 1;
    if(rca==1)return 1;if(rca<1)return 1;
    if(rca==1.)return 1;if(rca<1.)return 1;
    if(rcd==1)return 1;if(rcd<1)return 1;
    if(rcd==1.)return 1;if(rcd<1.)return 1;
    if(1==a)return 1;if(1<a)return 1;
    if(1.==a)return 1;if(1.<a)return 1;
    if(1==d)return 1;if(1<d)return 1;
    if(1.==d)return 1;if(1.<d)return 1;
    if(1==ca)return 1;if(1<ca)return 1;
    if(1.==ca)return 1;if(1.<ca)return 1;
    if(1==cd)return 1;if(1<cd)return 1;
    if(1.==cd)return 1;if(1.<cd)return 1;
    if(1==*pa)return 1;if(1<*pa)return 1;
    if(1.==*pa)return 1;if(1.<*pa)return 1;
    if(1==*pd)return 1;if(1<*pd)return 1;
    if(1.==*pd)return 1;if(1.<*pd)return 1;
    if(1==*pca)return 1;if(1<*pca)return 1;
    if(1.==*pca)return 1;if(1.<*pca)return 1;
    if(1==*pcd)return 1;if(1<*pcd)return 1;
    if(1.==*pcd)return 1;if(1.<*pcd)return 1;
    if(1==ra)return 1;if(1<ra)return 1;
    if(1.==ra)return 1;if(1.<ra)return 1;
    if(1==rd)return 1;if(1<rd)return 1;
    if(1.==rd)return 1;if(1.<rd)return 1;
    if(1==rca)return 1;if(1<rca)return 1;
    if(1.==rca)return 1;if(1.<rca)return 1;
    if(1==rcd)return 1;if(1<rcd)return 1;
    if(1.==rcd)return 1;if(1.<rcd)return 1;
    if((a==1)<<(a<1))return 1;
    if((a==1.)<<(a<1.))return 1;
    if((d==1)<<(d<1))return 1;
    if((d==1.)<<(d<1.))return 1;
    if((ca==1)<<(ca<1))return 1;
    if((ca==1.)<<(ca<1.))return 1;
    if((cd==1)<<(cd<1))return 1;
    if((cd==1.)<<(cd<1.))return 1;
    if((*pa==1)<<(*pa<1))return 1;
    if((*pa==1.)<<(*pa<1.))return 1;
    if((*pd==1)<<(*pd<1))return 1;
    if((*pd==1.)<<(*pd<1.))return 1;
    if((*pca==1)<<(*pca<1))return 1;
    if((*pca==1.)<<(*pca<1.))return 1;
    if((*pcd==1)<<(*pcd<1))return 1;
    if((*pcd==1.)<<(*pcd<1.))return 1;
    if((ra==1)<<(ra<1))return 1;
    if((ra==1.)<<(ra<1.))return 1;
    if((rd==1)<<(rd<1))return 1;
    if((rd==1.)<<(rd<1.))return 1;
    if((rca==1)<<(rca<1))return 1;
    if((rca==1.)<<(rca<1.))return 1;
    if((rcd==1)<<(rcd<1))return 1;
    if((rcd==1.)<<(rcd<1.))return 1;
    if((1==a)<<(1<a))return 1;
    if((1.==a)<<(1.<a))return 1;
    if((1==d)<<(1<d))return 1;
    if((1.==d)<<(1.<d))return 1;
    if((1==ca)<<(1<ca))return 1;
    if((1.==ca)<<(1.<ca))return 1;
    if((1==cd)<<(1<cd))return 1;
    if((1.==cd)<<(1.<cd))return 1;
    if((1==*pa)<<(1<*pa))return 1;
    if((1.==*pa)<<(1.<*pa))return 1;
    if((1==*pd)<<(1<*pd))return 1;
    if((1.==*pd)<<(1.<*pd))return 1;
    if((1==*pca)<<(1<*pca))return 1;
    if((1.==*pca)<<(1.<*pca))return 1;
    if((1==*pcd)<<(1<*pcd))return 1;
    if((1.==*pcd)<<(1.<*pcd))return 1;
    if((1==ra)<<(1<ra))return 1;
    if((1.==ra)<<(1.<ra))return 1;
    if((1==rd)<<(1<rd))return 1;
    if((1.==rd)<<(1.<rd))return 1;
    if((1==rca)<<(1<rca))return 1;
    if((1.==rca)<<(1.<rca))return 1;
    if((1==rcd)<<(1<rcd))return 1;
    if((1.==rcd)<<(1.<rcd))return 1;
    if(a==o)return 1;if(a<o)return 1;
    if(a==od)return 1;if(a<od)return 1;
    if(d==o)return 1;if(d<o)return 1;
    if(d==od)return 1;if(d<od)return 1;
    if(ca==o)return 1;if(ca<o)return 1;
    if(ca==od)return 1;if(ca<od)return 1;
    if(cd==o)return 1;if(cd<o)return 1;
    if(cd==od)return 1;if(cd<od)return 1;
    if(*pa==o)return 1;if(*pa<o)return 1;
    if(*pa==od)return 1;if(*pa<od)return 1;
    if(*pd==o)return 1;if(*pd<o)return 1;
    if(*pd==od)return 1;if(*pd<od)return 1;
    if(*pca==o)return 1;if(*pca<o)return 1;
    if(*pca==od)return 1;if(*pca<od)return 1;
    if(*pcd==o)return 1;if(*pcd<o)return 1;
    if(*pcd==od)return 1;if(*pcd<od)return 1;
    if(ra==o)return 1;if(ra<o)return 1;
    if(ra==od)return 1;if(ra<od)return 1;
    if(rd==o)return 1;if(rd<o)return 1;
    if(rd==od)return 1;if(rd<od)return 1;
    if(rca==o)return 1;if(rca<o)return 1;
    if(rca==od)return 1;if(rca<od)return 1;
    if(rcd==o)return 1;if(rcd<o)return 1;
    if(rcd==od)return 1;if(rcd<od)return 1;
    if(o==a)return 1;if(o<a)return 1;
    if(od==a)return 1;if(od<a)return 1;
    if(o==d)return 1;if(o<d)return 1;
    if(od==d)return 1;if(od<d)return 1;
    if(o==ca)return 1;if(o<ca)return 1;
    if(od==ca)return 1;if(od<ca)return 1;
    if(o==cd)return 1;if(o<cd)return 1;
    if(od==cd)return 1;if(od<cd)return 1;
    if(o==*pa)return 1;if(o<*pa)return 1;
    if(od==*pa)return 1;if(od<*pa)return 1;
    if(o==*pd)return 1;if(o<*pd)return 1;
    if(od==*pd)return 1;if(od<*pd)return 1;
    if(o==*pca)return 1;if(o<*pca)return 1;
    if(od==*pca)return 1;if(od<*pca)return 1;
    if(o==*pcd)return 1;if(o<*pcd)return 1;
    if(od==*pcd)return 1;if(od<*pcd)return 1;
    if(o==ra)return 1;if(o<ra)return 1;
    if(od==ra)return 1;if(od<ra)return 1;
    if(o==rd)return 1;if(o<rd)return 1;
    if(od==rd)return 1;if(od<rd)return 1;
    if(o==rca)return 1;if(o<rca)return 1;
    if(od==rca)return 1;if(od<rca)return 1;
    if(o==rcd)return 1;if(o<rcd)return 1;
    if(od==rcd)return 1;if(od<rcd)return 1;
    if((a==o)<<(a<o))return 1;
    if((a==od)<<(a<od))return 1;
    if((d==o)<<(d<o))return 1;
    if((d==od)<<(d<od))return 1;
    if((ca==o)<<(ca<o))return 1;
    if((ca==od)<<(ca<od))return 1;
    if((cd==o)<<(cd<o))return 1;
    if((cd==od)<<(cd<od))return 1;
    if((*pa==o)<<(*pa<o))return 1;
    if((*pa==od)<<(*pa<od))return 1;
    if((*pd==o)<<(*pd<o))return 1;
    if((*pd==od)<<(*pd<od))return 1;
    if((*pca==o)<<(*pca<o))return 1;
    if((*pca==od)<<(*pca<od))return 1;
    if((*pcd==o)<<(*pcd<o))return 1;
    if((*pcd==od)<<(*pcd<od))return 1;
    if((ra==o)<<(ra<o))return 1;
    if((ra==od)<<(ra<od))return 1;
    if((rd==o)<<(rd<o))return 1;
    if((rd==od)<<(rd<od))return 1;
    if((rca==o)<<(rca<o))return 1;
    if((rca==od)<<(rca<od))return 1;
    if((rcd==o)<<(rcd<o))return 1;
    if((rcd==od)<<(rcd<od))return 1;
    if((o==a)<<(o<a))return 1;
    if((od==a)<<(od<a))return 1;
    if((o==d)<<(o<d))return 1;
    if((od==d)<<(od<d))return 1;
    if((o==ca)<<(o<ca))return 1;
    if((od==ca)<<(od<ca))return 1;
    if((o==cd)<<(o<cd))return 1;
    if((od==cd)<<(od<cd))return 1;
    if((o==*pa)<<(o<*pa))return 1;
    if((od==*pa)<<(od<*pa))return 1;
    if((o==*pd)<<(o<*pd))return 1;
    if((od==*pd)<<(od<*pd))return 1;
    if((o==*pca)<<(o<*pca))return 1;
    if((od==*pca)<<(od<*pca))return 1;
    if((o==*pcd)<<(o<*pcd))return 1;
    if((od==*pcd)<<(od<*pcd))return 1;
    if((o==ra)<<(o<ra))return 1;
    if((od==ra)<<(od<ra))return 1;
    if((o==rd)<<(o<rd))return 1;
    if((od==rd)<<(od<rd))return 1;
    if((o==rca)<<(o<rca))return 1;
    if((od==rca)<<(od<rca))return 1;
    if((o==rcd)<<(o<rcd))return 1;
    if((od==rcd)<<(od<rcd))return 1;
}
