groups/csa/csafmt/csafmt_nonascii.t.cpp:1:0: warning: NA01: Non-ASCII characters
// abÞßëcd¶¥¶×ef
^~~
groups/csa/csafmt/csafmt_nonascii.t.cpp:1:0: warning: NA01: Non-ASCII characters
// abÞßëcd¶¥¶×ef
^~~~
groups/csa/csafmt/csafmt_nonascii.t.cpp:3:0: warning: NA01: Non-ASCII characters
    ¶¥×±
^~~~
groups/csa/csafmt/csafmt_nonascii.t.cpp:4:0: warning: NA01: Non-ASCII characters
    ¶¥×±®
^~~~~
groups/csa/csafmt/csafmt_nonascii.t.cpp:5:0: warning: NA01: Non-ASCII characters
    ¶¥×±®«
^~~~~~
5 warnings generated.
