groups/csa/csamisc/csamisc_constantreturn.t.cpp:12:0: warning: function f() has only one statement which returns the constant '0'
    return 0;
^
groups/csa/csamisc/csamisc_constantreturn.t.cpp:10:0: warning: declaration of f() (which always returns the constant 0)
int cool::csamisc::constantreturn::f()
^
In file included from groups/csa/csamisc/csamisc_constantreturn.t.cpp:8:
groups/csa/csamisc/csamisc_constantreturn.t.hpp:21:0: warning: declaration of f() (which always returns the constant 0)
            static int f();
^
groups/csa/csamisc/csamisc_constantreturn.t.cpp:17:0: warning: function g() has only one statement which returns the constant '13'
    return 5 + 8;
^
groups/csa/csamisc/csamisc_constantreturn.t.cpp:15:0: warning: declaration of g() (which always returns the constant 13)
int cool::csamisc::constantreturn::g()
^
In file included from groups/csa/csamisc/csamisc_constantreturn.t.cpp:8:
groups/csa/csamisc/csamisc_constantreturn.t.hpp:22:0: warning: declaration of g() (which always returns the constant 13)
            static int g();
^
6 warnings generated.
