groups/csa/csamisc/csamisc_contiguousswitch.t.cpp:35:0: warning: ES01: Empty switch statement
    switch (ac) {
^
groups/csa/csamisc/csamisc_contiguousswitch.t.cpp:40:0: warning: CS01: Test code should be within compound (brace-enclosed) statement
        ++ac;
^
groups/csa/csamisc/csamisc_contiguousswitch.t.cpp:39:0: warning: SD01: Switch starts with `default:` label
    default:
^
groups/csa/csamisc/csamisc_contiguousswitch.t.cpp:42:0: warning: SZ01: Switch should start with `case 0:`
    case 1:
^
groups/csa/csamisc/csamisc_contiguousswitch.t.cpp:51:0: warning: SZ01: Switch should start with `case 0:`
    case 1: {
^
groups/csa/csamisc/csamisc_contiguousswitch.t.cpp:54:0: warning: SZ01: Switch should start with `case 0:`
    case 0: {
^
groups/csa/csamisc/csamisc_contiguousswitch.t.cpp:54:0: warning: ZF02: `case 0:` should simply fall through to next case
groups/csa/csamisc/csamisc_contiguousswitch.t.cpp:63:0: warning: MD01: `default:` label in the middle of labels
    default: break;
^
groups/csa/csamisc/csamisc_contiguousswitch.t.cpp:70:0: warning: MD01: `default:` label in the middle of labels
    default: break;
^
groups/csa/csamisc/csamisc_contiguousswitch.t.cpp:77:0: warning: CS01: Test code should be within compound (brace-enclosed) statement
        switch (ac + 1) {
^
groups/csa/csamisc/csamisc_contiguousswitch.t.cpp:81:0: warning: MB01: Missing `break;` before this case
    case 5: break;
^
groups/csa/csamisc/csamisc_contiguousswitch.t.cpp:74:0: warning: ED01: Switch doesn't end with `default:` label
    switch (ac) // missing default
^
groups/csa/csamisc/csamisc_contiguousswitch.t.cpp:76:0: warning: ZF02: `case 0:` should simply fall through to next case
    case 0:
^
groups/csa/csamisc/csamisc_contiguousswitch.t.cpp:92:0: warning: LO01: Case label out of order: previous=100 value=5
    case 5: break;
^
groups/csa/csamisc/csamisc_contiguousswitch.t.cpp:106:0: warning: CS01: Test code should be within compound (brace-enclosed) statement
        ++ac;
^
groups/csa/csamisc/csamisc_contiguousswitch.t.cpp:112:0: warning: CS02: Test code should be within single compound (brace-enclosed) statement
        ++ac;
^
groups/csa/csamisc/csamisc_contiguousswitch.t.cpp:114:0: warning: MB01: Missing `break;` before this case
    case 10: {
^
17 warnings generated.
