In file included from groups/csa/csamisc/csamisc_memberdefinitioninclassdefinition.v.cpp:8:
groups/csa/csamisc/csamisc_memberdefinitioninclassdefinition.v.hpp:23:0: warning: CD01: Member function 'cool::csamisc::memberdefinitioninclassdefinition_foo::f' is defined in the class definition.
            void f() {}
^
groups/csa/csamisc/csamisc_memberdefinitioninclassdefinition.v.hpp:31:0: warning: CD01: Member function 'cool::csamisc::memberdefinitioninclassdefinition_bar::g' is defined in the class definition.
            void g() {}
^
groups/csa/csamisc/csamisc_memberdefinitioninclassdefinition.v.hpp:31:0: warning: CD01: Member function 'cool::csamisc::memberdefinitioninclassdefinition_bar<int>::g' is defined in the class definition.
3 warnings generated.
