In file included from groups/csa/csamisc/csamisc_memberdefinitioninclassdefinition.v.cpp:8:
groups/csa/csamisc/csamisc_memberdefinitioninclassdefinition.v.hpp:18:0: warning: member function 'cool::csamisc::memberdefinitioninclassdefinition_foo::f' is defined in the class definition.
            void f() {}
^
groups/csa/csamisc/csamisc_memberdefinitioninclassdefinition.v.hpp:26:0: warning: member function 'cool::csamisc::memberdefinitioninclassdefinition_bar<int>::g' is defined in the class definition.
            void g() {}
^
2 warnings generated.
