In file included from groups/csa/csabase/csabase_diagnosticfilter.t.cpp:8:
groups/csa/csabase/csabase_diagnosticfilter.t.hpp:29:0: warning: address of stack memory associated with local variable 'value' returned
    return &value;
^~~~~
groups/csa/csabase/csabase_diagnosticfilter.t.cpp:15:0: warning: address of stack memory associated with local variable 'value' returned
    return &value;
^~~~~
2 warnings generated.
