groups/csa/csatr/csatr_includeguard0.t.cpp:1:0: warning: TR03: Header file 'groups/csa/csatr/csatr_includeguard0.h' not accessible
// csatr_includeguard0.t.cpp                                          -*-C++-*-
^
groups/csa/csatr/csatr_includeguard0.t.cpp:4:0: warning: TR14: Missing include guard INCLUDED_CSATR_INCLUDEGUARD0
^
groups/csa/csatr/csatr_includeguard0.t.cpp:3:0: warning: SHO06: Missing include for bdes_ident.h
#include "csatr_includeguard0.t.h"
^
3 warnings generated.
