groups/csa/csatr/csatr_includeguard0.t.cpp:1:0: warning: FI01: Header file 'groups/csa/csatr/csatr_includeguard0.h' not accessible
// csatr_includeguard0.t.cpp                                          -*-C++-*-
^
groups/csa/csatr/csatr_includeguard0.t.cpp:4:0: warning: TR14: Missing include guard INCLUDED_CSATR_INCLUDEGUARD0
^
groups/csa/csatr/csatr_includeguard0.t.cpp:1:0: warning: TP14: TEST PLAN section is absent
// csatr_includeguard0.t.cpp                                          -*-C++-*-
^
3 warnings generated.
