In file included from groups/csa/csatr/csatr_usingdirectiveinheader.t.cpp:8:
groups/csa/csatr/csatr_usingdirectiveinheader.t.hpp:10:0: warning: TR16: namespace level using directive for 'cool' in header file
using namespace cool;
^
groups/csa/csatr/csatr_usingdirectiveinheader.t.hpp:14:0: warning: TR16: namespace level using directive for 'cool' in header file
    using namespace cool;
^
2 warnings generated.
