#!/bin/sh

# Script by which bde_build.pl can invoke bde_verify:
#   bde_build.pl -k -DCC={this} -DCXX={this} -c bde_verify ...

: ${VD:=/home/hrosen4/bde_verify}
: ${EXE:=$VD/Linux-gcc-4.8.1/bde_verify}
"$VD/scripts/bde_verify"                                                      \
    --nodefinc                                                                \
    --nodefdef                                                                \
    --config=$VD/bde_verify.cfg                                               \
    --exe=$EXE                                                                \
    $@

exit 0
