#!/usr/bin/env perl
# check_bos                                                          -*-perl-*-
#
# This is a wrapper script around bde_verify which checks that code is neutral
# with respect to BSL_OVERRIDES_STD.  It exits with a non-zero status if not.

use strict;
use warnings;

use Getopt::Long qw(:config no_ignore_case pass_through);

my $bv = 'bde_verify';
my $help;

my $command = join " \\\n ", $0, map { join "\\ ", split(/ /, $_, -1) } @ARGV;

sub usage()
{
    print "
usage: $0 [options] [bde_verify arguments]...
    -bv=bde_verify      path to bde_verify [$bv]
    -help               print this message

Invoked as:
$command
";
    exit(1);
}

GetOptions(
    'bv=s'   => \$bv,
    'help|?' => \$help,
) and !$help and $#ARGV >= 0 or usage();

my @args = (
    '-diagnose=main',
    '-cl=all off',
    '-cl=check bsl-overrides-std on',
    '-cl=suppress IS01 *',
    '-cl=suppress IS02 *',
    '-cl=suppress SB01 *',
    '-cl=suppress SB02 *',
    '-cl=suppress SB03 *',
    '-cl=set failstatus SB04',
);

exit 1 if system $bv, @ARGV, @args, '-ovr';
exit 1 if system $bv, @ARGV, @args, '-noovr';
