#!/usr/bin/perl -w
#  -*-perl-*- check
#  -----------------------------------------------------------------------------
#  Copyright 2012 Dietmar Kuehl http://www.dietmar-kuehl.de              
#  Modified  2013 Hyman Rosen (hrosen4@bloomberg.net)
#  Distributed under the Boost Software License, Version 1.0. (See file  
#  LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt).     
#  -----------------------------------------------------------------------------
# $Id$

use strict;
use Getopt::Long;

my $home     = "w:\\coolyser";
my $bb       = "c:\\BPCDEVTOOLS\\bde\\2.19.0";
my $config   = "$home\\coolyser.cfg";
my $debug    = "";
my $verbose  = "";
my $help     = "";

sub usage()
{
    print "
    usage: $0 [options] [additional compiler options] file.cpp ...
        --config=config_file     [$config]  
        --bb=dir                 [$bb]
        --debug
        --verbose
        --help

";
    exit(1);
}

GetOptions(
    'bb=s'       => \$bb,
    'config=s'   => \$config,
    'debug'      => \$debug,
    'help|?'     => \$help,
    'verbose'    => \$verbose,
) and !$help and $#ARGV >= 0 or usage();

my @config = ("-plugin-arg-coolyse", "config=$config") if $config ne "";
my @debug  = ("-plugin-arg-coolyse", "debug-on")       if $debug;

my @lflags = (
    "color-diagnostics",
    "cxx-exceptions",
    "diagnostics-show-name",
    "diagnostics-show-option",
    "ms-compatibility",
    "ms-extensions",
    "msc-version=1800",
);
@lflags = map { "-f$_" } @lflags;

my @wflags = (
    "everything",
);
@wflags = map { "-W$_" } @wflags;

my @defs = (
    "BDE_BUILD_TARGET_DBG",
    "BDE_BUILD_TARGET_EXC",
    "BDE_BUILD_TARGET_MT",
    "_CRT_SECURE_NO_DEPRECATE",
    "_SCL_SECURE_NO_DEPRECATE",
    "NOMINMAX",
    "NOGDI",
    "_WIN32_WINNT=0x0500",
    "WINVER=0x0500",
    "DEBUG",
    "_MT",
    "BSLS_IDENT_OFF",
    "BSL_OVERRIDES_STD",
    "BDE_OMIT_INTERNAL_DEPRECATED",
    "_STLP_USE_STATIC_LIB",
    "_STLP_HAS_NATIVE_FLOAT_ABS",
    "BDE_DCL=",
    "BSL_DCL=",
);
@defs = map { "-D$_" } @defs;

my @incs;
for (@ARGV) {
    if (m{^(.*)[/\\].*$}) {
        push(@incs, $1) unless grep($1, @incs);
    }
}
push(@incs, (
    ".",
    "$bb\\include",
    "$bb\\include\\bsl+stdhdrs",
    "c:\\Program Files (x86)\\Microsoft Visual Studio 11.0\\VC\\include",
));
@incs = map { ("-I", $_, "-cxx-isystem", $_ ) } @incs;

my @command = (
    "c:\\bde-verify\\Debug\\BDEVerify.exe",
    "-cc1",
    "-std=c++11",
    "-plugin",
    "coolyse",
    @debug,
    @config,
    @defs,
    @incs,
    @lflags,
    @wflags,
    @ARGV,
);

print join(' ', @command), "\n" if $verbose;

exec @command;
