#!/usr/bin/perl -w
#  -*-perl-*- check
#  -----------------------------------------------------------------------------
#  Copyright 2012 Dietmar Kuehl http://www.dietmar-kuehl.de              
#  Modified  2013 Hyman Rosen (hrosen4@bloomberg.net)
#  Distributed under the Boost Software License, Version 1.0. (See file  
#  LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt).     
#  -----------------------------------------------------------------------------
# $Id$

use strict;
use Getopt::Long qw(:config no_ignore_case);

my $home     = "/home/hrosen4/coolyser";
#my $llvm     = "/bb/mbigc/mbig816/build/Release+Asserts";
my $llvm     = "/bb/mbigc/mbig816/llvm-svn/install";
my $bb       = "/bb/build/share/packages/refroot/amd64/unstable/bb";
my $config   = "$home/coolyser.cfg";
#my $lib      = "$home/Linux-clang-3.3/coolyser.so";
my $lib      = "$home/Linux-clang-3.5/coolyser.so";
my $debug    = "";
my $verbose  = "";
my $help     = "";
my $definc   = 1;
my $defdef   = 1;
my @incs;
my @defs;
my @wflags;
my @lflags = (
    "color-diagnostics",
    "cxx-exceptions",
    "diagnostics-show-name",
    "diagnostics-show-option",
);
my $dummy;
my @dummy;

sub usage()
{
    print "
    usage: $0 [options] [additional compiler options] file.cpp ...
        -I{directory}
        -D{macro}
        -W{warning}
        -f{flag}
        --config=config_file     [$config]  
        --bb=dir                 [$bb]
        --lib=coolyser.so        [$lib]
        --llvm=dir               [$llvm]
        --[no]definc             [$definc]
        --[no]defdef             [$defdef]
        --debug
        --verbose
        --help

";
    exit(1);
}

@ARGV = map { /^(-+[DIOWf])(.+)/ ? ($1, $2) : $_ } @ARGV;

GetOptions(
    'bb=s'       => \$bb,
    'config=s'   => \$config,
    'debug'      => \$debug,
    'help|?'     => \$help,
    'lib=s'      => \$lib,
    'llvm=s'     => \$llvm,
    'verbose|v'  => \$verbose,
    'definc!'    => \$definc,
    'defdef!'    => \$defdef,
    "I=s"        => \@incs,
    "D=s"        => \@defs,
    "W=s"        => \@wflags,
    "f=s"        => \@lflags,
    "m32!"       => \$dummy,
    "m64!"       => \$dummy,
    "pipe!"      => \$dummy,
    "pthread!"   => \$dummy,
    "O=s"        => \@dummy,
    "MMD!"       => \$dummy,
    "MF=s"       => \@dummy,
    "c!"         => \$dummy,
    "o=s"        => \@dummy,
) and !$help and $#ARGV >= 0 or usage();

my @config = ("-plugin-arg-coolyse", "config=$config") if $config ne "";
my @debug  = ("-plugin-arg-coolyse", "debug-on")       if $debug;

@lflags = map { "-f$_" if $_ ne "no-strict-aliasing" } @lflags;
@wflags = map { "-W$_" } @wflags;

push(@defs, (
    "BB_THREADED",
    "BDE_BUILD_TARGET_DBG",
    "BDE_BUILD_TARGET_EXC",
    "BDE_BUILD_TARGET_MT",
    "BSL_OVERRIDES_STD",
    "_LINUX_SOURCE",
    "_REENTRANT",
    "_SYS_SYSMACROS_H",
    "_THREAD_SAFE",
)) if $defdef;
@defs = map { "-D$_" } @defs;

for (@ARGV) {
    if (m{^(.*)/.*$}) {
        push(@incs, $1) unless grep($1, @incs);
    }
}
push(@incs, (
    ".",
    "$bb/include",
    "$bb/include/stlport",
)) if $definc;
push(@incs, map { chomp; $_; }
            qx{ $llvm/bin/clang++ -xc++ -E -v /dev/null 2>&1 |
                /opt/swt/bin/sed -n '/^ [/]/s/ //p'});
@incs = map { ("-I", $_, "-cxx-isystem", $_ ) } @incs;

my @command = (
    "$llvm/bin/clang",
    "-cc1",
    "-load",
    "$lib",
    "-plugin",
    "coolyse",
    @debug,
    @config,
    @defs,
    @incs,
    @lflags,
    @wflags,
    @ARGV);

print join(' ', @command), "\n" if $verbose;

exec @command;
