#!/usr/bin/perl -w
#  -*-perl-*- check
#  -----------------------------------------------------------------------------
#  Copyright 2012 Dietmar Kuehl http://www.dietmar-kuehl.de              
#  Modified  2013 Hyman Rosen (hrosen4@bloomberg.net)
#  Distributed under the Boost Software License, Version 1.0. (See file  
#  LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt).     
#  -----------------------------------------------------------------------------
# $Id$

use strict;
use Getopt::Long;

my $home     = "/home/hrosen4/coolyser";
my $llvm     = "/bb/mbigc/mbig816/build/Release+Asserts";
my $bb       = "/bb/build/share/packages/refroot/amd64/unstable/bb";
my $config   = "$home/coolyser.cfg";
my $lib      = "$home/Linux-clang-3.3/coolyser.so";
my $debug    = "";
my $verbose  = "";
my $help     = "";

sub usage()
{
    print "
    usage: $0 [options] [additional compiler options] file.cpp ...
        --config=config_file     [$config]  
        --bb=dir                 [$bb]
        --lib=coolyser.so        [$lib]
        --llvm=dir               [$llvm]
        --debug
        --verbose
        --help

";
    exit(1);
}

GetOptions(
    'bb=s'       => \$bb,
    'config=s'   => \$config,
    'debug'      => \$debug,
    'help|?'     => \$help,
    'lib=s'      => \$lib,
    'llvm=s'     => \$llvm,
    'verbose'    => \$verbose,
) and !$help and $#ARGV >= 0 or usage();

$config = "-plugin-arg-coolyse config=$config" if $config ne "";
$debug  = "-plugin-arg-coolyse debug-on"       if $debug;

my @lflags = (
    "color-diagnostics",
    "cxx-exceptions",
    "diagnostics-show-name",
    "diagnostics-show-option",
);
my $lflags  = join(" ", map("-f$_", @lflags));

my @wflags = (
    #"everything",
);
my $wflags  = join(" ", map("-W$_", @wflags));

my @defs = (
    "BB_THREADED",
    "BDE_BUILD_TARGET_DBG",
    "BDE_BUILD_TARGET_EXC",
    "BDE_BUILD_TARGET_MT",
    "BSL_OVERRIDES_STD",
    "_LINUX_SOURCE",
    "_REENTRANT",
    "_SYS_SYSMACROS_H",
    "_THREAD_SAFE",
);

my @incs;
for (@ARGV) {
    if (m{^(.*)/.*$}) {
        push(@incs, $1) unless grep($1, @incs);
    }
}
push(@incs, (
    ".",
    "$bb/include",
    "$bb/include/stlport",
    "/usr/include",
    "/usr/include/c++/4.4.4",
    "/usr/include/c++/4.4.4/backward",
    "/usr/include/c++/4.4.4/x86_64-redhat-linux6E/32",
    "/usr/lib/gcc/x86_64-redhat-linux6E/4.4.4/include",
    "/usr/lib/gcc/x86_64-redhat-linux/4.1.2/include",
));

my $flags = join(' ', map("-D$_", @defs), map("-I$_ -isystem $_", @incs));

my $command = "$llvm/bin/clang -cc1 -load $lib -plugin coolyse $debug $config $flags $lflags $wflags " . join(" ", @ARGV);

print "$command\n" if $verbose;

exec $command;
