#!/usr/bin/perl -w
#  -*-perl-*- check
#  -----------------------------------------------------------------------------
#  Copyright 2012 Dietmar Kuehl http://www.dietmar-kuehl.de              
#  Modified  2013 Hyman Rosen (hrosen4@bloomberg.net)
#  Distributed under the Boost Software License, Version 1.0. (See file  
#  LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt).     
#  -----------------------------------------------------------------------------
# $Id$

use strict;
use Getopt::Long;

my $home     = "/home/hrosen4/coolyser";
#my $llvm     = "/bb/mbigc/mbig816/build/Release+Asserts";
my $llvm     = "/bb/mbigc/mbig816/llvm-svn/install";
my $bb       = "/bb/build/share/packages/refroot/amd64/unstable/bb";
my $config   = "$home/coolyser.cfg";
#my $lib      = "$home/Linux-clang-3.3/coolyser.so";
my $lib      = "$home/Linux-clang-3.5/coolyser.so";
my $debug    = "";
my $verbose  = "";
my $help     = "";

sub usage()
{
    print "
    usage: $0 [options] [additional compiler options] file.cpp ...
        --config=config_file     [$config]  
        --bb=dir                 [$bb]
        --lib=coolyser.so        [$lib]
        --llvm=dir               [$llvm]
        --debug
        --verbose
        --help

";
    exit(1);
}

GetOptions(
    'bb=s'       => \$bb,
    'config=s'   => \$config,
    'debug'      => \$debug,
    'help|?'     => \$help,
    'lib=s'      => \$lib,
    'llvm=s'     => \$llvm,
    'verbose'    => \$verbose,
) and !$help and $#ARGV >= 0 or usage();

my @config = ("-plugin-arg-coolyse", "config=$config") if $config ne "";
my @debug  = ("-plugin-arg-coolyse", "debug-on")       if $debug;

my @lflags = (
    "color-diagnostics",
    "cxx-exceptions",
    "diagnostics-show-name",
    "diagnostics-show-option",
);
@lflags = map { "-f$_" } @lflags;

my @wflags = (
);
@wflags = map { "-W$_" } @wflags;

my @defs = (
    "BB_THREADED",
    "BDE_BUILD_TARGET_DBG",
    "BDE_BUILD_TARGET_EXC",
    "BDE_BUILD_TARGET_MT",
    "BSL_OVERRIDES_STD",
    "_LINUX_SOURCE",
    "_REENTRANT",
    "_SYS_SYSMACROS_H",
    "_THREAD_SAFE",
);
@defs = map { "-D$_" } @defs;

my @incs;
for (@ARGV) {
    if (m{^(.*)/.*$}) {
        push(@incs, $1) unless grep($1, @incs);
    }
}
push(@incs, (
    ".",
    "$bb/include",
    "$bb/include/stlport",
));
push(@incs, map { chomp; $_; }
            qx{ $llvm/bin/clang++ -xc++ -E -v /dev/null 2>&1 |
                /opt/swt/bin/sed -n '/^ [/]/s/ //p'});
@incs = map { ("-I", $_, "-cxx-isystem", $_ ) } @incs;

my @command = (
    "$llvm/bin/clang",
    "-cc1",
    "-load",
    "$lib",
    "-plugin",
    "coolyse",
    @debug,
    @config,
    @defs,
    @incs,
    @lflags,
    @wflags,
    @ARGV);

print join(' ', @command), "\n" if $verbose;

exec @command;
