#!/usr/bin/env bash

# Script invoked by Jenkins to run bdeverify.

echo "INVOKED ARGS ARE <<$*>>"

NODE=$1
HOST=${NODE%%+++*}
UFID=$2
WORKSPACE=$3
BSL_FLAVOUR=${4-internal}
TARGET_UOR=${5-bsl bde bce bte bae bbe bsi}

JOBS=8
if [[ "$UFID" == "dbg_exc_mt" && "$NODE" == "nylnxbldo2+++gcc-4.3.2" ]]
then
    JOBS=16
fi

VD=$WORKSPACE/bde-verify
EXE=$VD/Linux-clang-3.5/bdeverify
export VD EXE

BDEVERIFY="$VD/scripts/build_verify"

function ts () { date +"%Y%m%d-%H%M%S"; }

echo "======================================================"
echo "Running on node '$NODE' (host $HOST)"
echo "'hostname'" is $(hostname)
echo "UFID is '$UFID' (JOBS is '$JOBS')"
echo "WORKSPACE is '$WORKSPACE'"
echo "BSL flavour is '$BSL_FLAVOUR'"
echo "Building target '$BUILD' (CMD_ARG is '$CMD_ARG')"
echo "Building UOR '$TARGET_UOR'"
echo "======================================================"

BDE_ROOT=$WORKSPACE/bde-core
BDE_PATH=\
$WORKSPACE/bde-tools:\
$WORKSPACE/bsl-${BSL_FLAVOUR}:\
$BDE_ROOT:\
$WORKSPACE/bde-bdx:\
$WORKSPACE/bde-bb

export BDE_PATH BDE_ROOT

# /opt/swt/bin for gmake
# /usr/ccs/bin for ar on Sun
PATH=/opt/swt/bin:/usr/ccs/bin:$PATH

HEADER_LOG=$WORKSPACE/log-header-deploy.`ts`

echo "++++++++++++++++++++++  $(ts):" \
     "Deploying headers for all uors (logged to $HEADER_LOG)"

$WORKSPACE/bde-tools/bin/bde_build.pl \
    -k -c bdeverify -DCC="$BDEVERIFY" -DCXX="$BDEVERIFY" \
    -O -Re -j${JOBS} -t $UFID -Minstall_include $TARGET_UOR > $HEADER_LOG 2>&1

RESULT=$?
if [ $RESULT -ne 0 ]
then
    echo "++++++++++++++++++++++  FAIL FAIL FAIL " \
         "Deploying headers for $TARGET_UOR - error $RESULT"
    echo See $HEADER_LOG

    echo "Tail end of $HEADER_LOG:"
    tail -10 $HEADER_LOG

    exit $RESULT
else
    rm $HEADER_LOG
fi

echo "++++++++++++++++++++++  $(ts) Building $TARGET_UOR"

$WORKSPACE/bde-tools/bin/bde_build.pl \
    -k -c bdeverify -DCC="$BDEVERIFY" -DCXX="$BDEVERIFY" \
    -O -Re -j${JOBS} -t $UFID $TARGET_UOR

exit 0

RESULT=$?
if [ $RESULT -ne 0 ]
then
    echo "++++++++++++++++++++++  FAIL FAIL FAIL " \
         "Building $TARGET_UOR - error $RESULT"
    exit $RESULT
fi
