#!/usr/bin/perl -w
#  -*-perl-*- check
#  -----------------------------------------------------------------------------
#  Copyright 2012 Dietmar Kuehl http://www.dietmar-kuehl.de              
#  Distributed under the Boost Software License, Version 1.0. (See file  
#  LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt).     
#  -----------------------------------------------------------------------------
# $Id$

use strict;

sub mkdirhier
{
    my $dir = shift;
    if (! -d $dir && $dir ne "")
    {
    	my $parent = $dir;
	if ($dir =~ /\//)
        {	
            $parent =~ s/\/[^\/]*$//;
            mkdirhier($parent);
        }
	mkdir($dir);
    }
}

for my $f (@ARGV)
{
    mkdirhier($f);
}
