testpt.t.cpp:78:30: warning: TP27: Method not called in test driver
        template <class T> T f3u();
                             ^
testpt.t.cpp:79:30: warning: TP27: Method not called in test driver
        template <int N> int f4u();
                             ^
testpt.t.cpp:15:1: warning: TP26: Tested class has a function named 'f3u' but the test plan has none
// [ 1] joe::f1co();
^
testpt.t.cpp:15:1: warning: TP26: Tested class has a function named 'f4u' but the test plan has none
4 warnings generated.
