h.cpp:10:8: warning: AL01: Class 'X' needs allocator() method
struct X {
       ^
h.cpp:14:1: note: AL01: Allocator method definition for class X

  public:
    // PUBLIC ACCESSORS
    bslma::Allocator *allocator() const;

};
^
h.cpp:10:8: warning: AP02: Class 'X' needs d_allocator_p member
struct X {
       ^
h.cpp:14:1: note: AP02: Allocator member declaration for class X

  private:
    // PRIVATE DATA
    bslma::Allocator *d_allocator_p;

};
^
2 warnings generated.
