In file included from csamisc_memberdefinitioninclassdefinition.v.cpp:8:
./csamisc_memberdefinitioninclassdefinition.v.hpp:23:18: warning: CD01: Member function 'bde_verify::csamisc::memberdefinitioninclassdefinition_foo::f' is defined in the class definition.
            void f() {}
                 ^
./csamisc_memberdefinitioninclassdefinition.v.hpp:31:18: warning: CD01: Member function 'bde_verify::csamisc::memberdefinitioninclassdefinition_bar::g' is defined in the class definition.
            void g() {}
                 ^
2 warnings generated.
